comau_ik_solver:
  # supported types: ComauNJ220IkSolver, ComauNJ370IkSolver, ComauIkSolver
  type: ik_solver/Comau_NJ_Generic_IkSolver
  base_frame: base_link #world # base frame of the chain
  flange_frame: flange # end frame of the chain

  tool_frame: flange # destination frame of the IK (it should be rigid attached to flange_frame)
  desired_solutions: 8 # number of desired solution
  joint_names:
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6
